CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE dev_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    work_content TEXT NOT NULL,
    problem_content TEXT,
    solution_content TEXT,
    learned_content TEXT,
    status VARCHAR(20) NOT NULL,
    record_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_dev_records PRIMARY KEY (record_id),
    CONSTRAINT fk_dev_records_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT ck_dev_records_status
        CHECK (status IN ('EASY', 'NORMAL', 'DIFFICULT'))
);

CREATE TABLE tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tag_name VARCHAR(100) NOT NULL,
    category VARCHAR(20) NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (tag_id),
    CONSTRAINT ck_tags_category
        CHECK (category IN ('LANGUAGE', 'FRAMEWORK', 'DB', 'INFRA', 'ISSUE', 'ETC'))
);

CREATE TABLE record_tags (
    record_tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    record_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_record_tags PRIMARY KEY (record_tag_id),
    CONSTRAINT fk_record_tags_record
        FOREIGN KEY (record_id) REFERENCES dev_records (record_id) ON DELETE CASCADE,
    CONSTRAINT fk_record_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE,
    CONSTRAINT uq_record_tags_record_tag UNIQUE (record_id, tag_id)
);

CREATE TABLE summaries (
    summary_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    record_id BIGINT NOT NULL,
    summary_title VARCHAR(255) NOT NULL,
    summary_content TEXT NOT NULL,
    key_point TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_summaries PRIMARY KEY (summary_id),
    CONSTRAINT fk_summaries_record
        FOREIGN KEY (record_id) REFERENCES dev_records (record_id) ON DELETE CASCADE,
    CONSTRAINT uq_summaries_record UNIQUE (record_id)
);

CREATE TABLE weekly_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    weekly_summary TEXT NOT NULL,
    main_tasks TEXT NOT NULL,
    main_issues TEXT NOT NULL,
    learned_points TEXT NOT NULL,
    next_actions TEXT NOT NULL,
    created_type VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_weekly_reports PRIMARY KEY (report_id),
    CONSTRAINT fk_weekly_reports_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT ck_weekly_reports_created_type
        CHECK (created_type IN ('MANUAL', 'BATCH')),
    CONSTRAINT ck_weekly_reports_date_range
        CHECK (start_date <= end_date)
);

CREATE TABLE presentations (
    presentation_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    key_contents TEXT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    source_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_presentations PRIMARY KEY (presentation_id),
    CONSTRAINT fk_presentations_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT ck_presentations_source_type
        CHECK (source_type IN ('DEV_RECORD', 'WEEKLY_REPORT'))
);

CREATE INDEX idx_dev_records_user_record_date
    ON dev_records (user_id, record_date DESC);

CREATE INDEX idx_record_tags_tag
    ON record_tags (tag_id);

CREATE INDEX idx_weekly_reports_user_period
    ON weekly_reports (user_id, start_date, end_date);

CREATE INDEX idx_presentations_user_created_at
    ON presentations (user_id, created_at DESC);

CREATE INDEX idx_presentations_source
    ON presentations (source_type, source_id);
